### ISSUE TITLE
Local-TLD blocks vhost resolution

### ISSUE THREAD

**Issue by espy** [hoodiehq-archive/local-tld#5]
Vhosts are no longer accessible when running a Hoodie app, and even after stopping the app. This helps:

```
sudo launchctl unload ~/Library/LaunchAgents/ie.hood.local-tld-service.plist
sudo ipfw flush
```

Direct access to localhost is only occasionally affected by Hoodie, but vhosts are always blocked.

**Comment by janl** [comment]
fixed in local-tld 3.0.1 (I hope :)

To install:

```
npm install -g local-tld
```

Hoodie apps and other services on port 80 like apache httpd should just work now.

This doesn’t create compat with pow yet though.

**Comment by janl** [comment]
Fixed in 69c255a7b3536c338285d710163edd94ed869578

**Comment by espy** [comment]
Localhost and local-tld now work in parallel, which is great, but vhosts are still broken. The Hoodie must be stopped, unloaded with `launchctl unload ~/Library/LaunchAgents/ie.hood.local-tld-service.plist` and `sudo ipfw flush`ed before vhosts will work.

**Comment by janl** [comment]
note for @janl: parse /etc/hosts for ^127.0.0.1 entries and route them as well.

**Comment by espy** [comment]
Another note for @janl: Don't forget IPv6:
::1
fe80::1%lo0

**Comment by gryzzly** [comment]
Will buzz here so that you guys know people run into this problem.

**Comment by espy** [comment]
Just to sum this up: Here's a temporary workaround for the time being.

To get your vhosts back: `$ sudo ipfw flush`

To get local-tld back: `$ npm install -g local-tld`

To find out which state you're in: `$ sudo ipfw list`
If this includes something like "00100 fwd 127.0.0.1,5999 tcp from any to me dst-port 80 in", local-tld is currently running and might be blocking your vhosts.

**Comment by gryzzly** [comment]
Perhaps it'd make sense for this to be in README for Hoodie esp. since it's advertised for front end people who often work with built-in apache and vhosts. Many I think won't realize their vhosts stopped working because of hoodie install (I happened to have some experience with POW and read README for npm module so I had an idea it could mess it up).

**Comment by espy** [comment]
Good idea, done! Thanks :)

**Comment by janl** [comment]
I looked into it a bit and didn’t find a satisfying solution. Even Pow has a note up front in the docs about this.

I will keep working on this on this side, but I don’t have high hopes.

**Comment by espy** [comment]
Ok then. Alternatives: 
- Better documentation, so no-one runs into this unprepared. I'd also add this to the output each `$ hoodie start` prints out.
- Hoodie automatically deactivating local-tld when all hoodie instances are stopped, and reactivating it as soon as one starts. No idea if this is possible.

The only thing this would really break is using a Hoodie API from a vhosted project, which is a pretty rare edge case, I'd assume.

**Comment by janl** [comment]
I think the “turn on when required” option can work. +1 for docs for now.

**Comment by Phunky** [comment]
I don't seem to suffer from this while running hoodie, although I am running homebrew versions of Apache and PHP.

**Comment by allaire** [comment]
just got bit by that.

Currently to make my vhosts work, I do:

`launchctl unload ~/Library/LaunchAgents/ie.hood.local-tld-service.plist && sudo ipfw flush`

And to make local-tld work, I do:

`npm install -g local-tld`

Is there anything simplier/cleaner?

Current aliases:

```
alias iltld='npm install -g local-tld'
alias ultld='launchctl unload ~/Library/LaunchAgents/ie.hood.local-tld-service.plist && sudo ipfw flush'
```

or

```
alias iltld='npm install -g local-tld'
alias ultld='npm uninstall -g local-tld && sudo ipfw flush'
```

No idea which one is 'cleaner'... @espy just `sudo ipfw flush` is not enough, you also have to stop the service (which is a bit weird isn't?).

cc @janl

**Comment by allaire** [comment]
I can PR some doc in the README with the cleaner aliases set above if you want, let me know which aliases you prefer!

**Comment by janl** [comment]
sure, why not! :)

**Comment by allaire** [comment]
@janl Which ones? :) Also is it normal that a simple `sudo ipfw flush` does not turn it off? I thought everything was passing by the firewall rule?

**Comment by janl** [comment]
How about this?

``` shell
alias ltld-on='npm install -g local-tld'
alias ltld-off='launchctl unload ~/Library/LaunchAgents/ie.hood.local-tld-service.plist && sudo ipfw flush'
```

**Comment by allaire** [comment]
That seems good. @janl Why do we  have to stop the service in order to turn it off?

**Comment by janl** [comment]
how else would you turn it off? :) this is the equivalent of `apachectl stop`.

**Comment by allaire** [comment]
Well, if the firewall don't route any traffic to it (by doing `sudo ipfw flush`), how come it's still working? :)

**Comment by janl** [comment]
sounds like that shouldn’t happen in fact.

**Comment by allaire** [comment]
My thoughts exactly, that's why I'm wondering why the service should also be stopped!

**Comment by janl** [comment]
can you double check that you can actually repeat this? I’ve never seen it :)

**Comment by allaire** [comment]
Yes, only `sudo ipfw flush` does not release 127.0.0.1 to apache, can you try it too?

**Comment by janl** [comment]
sorry, no time atm :)
